---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: monitoring-config
  namespace: flux-system
spec:
  interval: 1h0m0s
  path: ./manifests/monitoring/monitoring-config
  prune: true
  dependsOn:
    - name: monitoring-stack
  sourceRef:
    kind: GitRepository
    name: monitoring

