---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: monitoring-stack
  namespace: flux-system
spec:
  healthChecks:
  - kind: Deployment
    name: kube-prometheus-stack-operator
    namespace: monitoring
  - kind: Deployment
    name: kube-prometheus-stack-grafana
    namespace: monitoring
  interval: 1h0m0s
  path: ./manifests/monitoring/kube-prometheus-stack
  prune: true
  sourceRef:
    kind: GitRepository
    name: monitoring
  timeout: 2m0s

