apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: 29-metallb
  namespace: flux-system
spec:
  interval: 60m0s
  retryInterval: 1m0s
  timeout: 4m0s
  #suspend: false
  path: ./apps/metallb
  prune: true
 #wait: true
  sourceRef:
    kind: GitRepository
    name: flux-sync
