apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: 75-deis
  namespace: flux-system
spec:
  interval: 60m0s
  retryInterval: 6m0s
  timeout: 4m0s
  sourceRef:
    kind: GitRepository
    name: flux-sync
  path: ./apps/hephy
  dependsOn:
  # - name: 11-certificates
    - name: 12-persistence
    - name: infrastructure
    - name: traefik-api-crds
  prune: true
 #wait: false
 #suspend: false
