apiVersion: v1
data:
  current_release: "20220102205415" # {"$imagepolicy": "kubytest-production:kuby-tester:tag"}
  # current_assets_release: "20211231051654-assets" # --- XXX : "kubytest-production:kuby-tester-assets:tag"
kind: ConfigMap
metadata:
  name: kubytest-release-config
  namespace: flux-system
