apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: 50-metrics-server
  namespace: flux-system
spec:
  interval: 60m0s
  retryInterval: 6m0s
  timeout: 4m0s
  #suspend: false
  path: ./apps/metrics-server
  prune: true
 #wait: true
  sourceRef:
    kind: GitRepository
    name: flux-sync
