apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: 30-ingress-nginx
  namespace: flux-system
spec:
  interval: 173m
  retryInterval: 5m0s
  timeout: 3m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps/ingress-nginx
  dependsOn:
    - name: 29-metallb
  prune: true
 #wait: true
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: ingress-internal-ingress-nginx-controller
      namespace: ingress-nginx
    - apiVersion: apps/v1
      kind: Deployment
      name: ingress-public-ingress-nginx-controller
      namespace: ingress-nginx
