apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: persistence
  namespace: flux-system
spec:
  interval: 10m0s
  retryInterval: 6m0s
  timeout: 4m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./persistence
  prune: false
  wait: false
 #suspend: false
