apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: kube-oidc-proxy
  namespace: traefik-staging
spec:
  entryPoints:
  - web
  routes:
  - kind: Rule
    match: Host(`kube.sso.moo.hephy.pro`)
    services:
    - kind: Service
      name: kube-sso-public-challenge
      namespace: traefik-staging
      port: 80
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: kube-oidc-proxy
  namespace: traefik-staging
spec:
  entryPoints:
    - websecure
  routes:
  - match: HostSNI(`kube.sso.moo.hephy.pro`)
    services:
    - name: kube-oidc-proxy
      namespace: kube-oidc-proxy
      port: 443
  tls:
    passthrough: true
