apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
#- cluster-api/aks-kuberkingdon2.yaml
#- cluster-api/gke-cluster-1.yaml
- chartmuseum
- cluster-api/flux-kustomization.yaml
- cluster-api/gitrepository.yaml
- flux-system
- flux-system-extras/gitno-hephy-pro-ingress.yaml
- flux-system-extras/git-webhook-receiver.yaml
- flux-system-extras/image-webhook-receiver.yaml
- flux-system-extras/git-commit-status-alert-provider.yaml
- flux-system-extras/on-call-webapp-alert.yaml
- flux-system-extras/podinfo-image-webhook-receiver.yaml
- flux-system-extras/slack-notification.yaml
- ../../base/staging
- harbor
- hephy/flux-kustomization.yaml
- hephy/namespace.yaml
- metallb/flux-kustomization.yaml
- metrics-server/flux-kustomization.yaml
- minio-stage/flux-kustomization.yaml
- minio-stage/namespace.yaml
- minio-stage/juozas-namespace.yaml
- my-secrets/my-secrets-kustomization.yaml
- namespaces
- openvpn-as
- ingress-nginx
- cert-manager
- keycloak
- kube-oidc-proxy
- persistence
- routers
- certificates
- monitoring
- kuby-test/flux-kustomization.yaml
- kuby-test/config.yaml
